server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boardtest?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
